### ISSUE TITLE
rtx-1.0: Does not appear to activate rtx feature

### ISSUE THREAD

**Issue by AtomicStryker** [emoose/VideoRenderer#3]
Windows 10 22H2 19045.2604, HDR is off
Nvidia driver 531.18
GPU is RTX 4090
Display is a 4K 120Hz Monitor, HDR off

Testing Software:
Current Chrome + Youtube
MPC-BE x64 1.6.6 portable
MPC-HC x64 2.0.016 (K-Lite Codec Pack)
VLC as definitely not-optimized comparator

I found the easiest way to detect if the RTX feature is active or not is to check the GPU power draw.
There is a notable bump whenever upscaling is happening.

This is me playing a youtube video in chrome with RTX SR 4 active:
![image](https://user-images.githubusercontent.com/1858566/222257211-2508d538-118a-49c8-aa24-74d85f136acd.png)
Power draw goes from 27W to 80W.
Rendering video without RTX SR does not increase power draw above 27W.

So i followed the instructions, but neither MPC-HC nor MPC-BE x64 1.6.6 portable show an observable difference in image quality (compared with VLC) or a bump in GPU power usage.

Here are my settings:
![image](https://user-images.githubusercontent.com/1858566/222257802-e5b1ca93-1b7f-4436-a114-c81abd7e192e.png)

**Comment by AtomicStryker** [comment]
Update: I saw the reddit post saying it appears to only work on some videos, so i tried a bunch and found some it does work for.

When MPC-BE has the "GPU" marker in the bottom right, for H.264 D11 content, then it appears to be active.

Oddly enough, the same video and renderer in MPC-HC does not get superres. It does report as "native H/W D11"

**Comment by clsid2** [comment]
You can change the hardware decoder in the settings of the internal video decoder of MPC-HC.
Options > Internal Filters > Video Decoder
However, it should theoretically work with all of them.
