### ISSUE TITLE
Screen goes black in fullscreen until MPC restart

### ISSUE THREAD

**Issue by freakedenough** [emoose/VideoRenderer#50]
MPC-HC 2.3.7 x64 (installed via K-Lite Codec Pack Mega)
Video Renderer 1.2
Upscaling x4, RTX HDR on
RTX4070 Laptop
Win11 HDR On

When I start playing a video and go to full screen right away, the player stops displaying the video altogether. Returning to windowed mode doesn't help; I must restart MPC-HC. The video codec doesn't seem to matter (H.264, H.265, AV1, and VP9 all experience this issue). If I wait about 10 seconds after starting playback before going fullscreen, then going to fullscreen works every time for the whole remaining playback time.

**Comment by clsid2** [comment]
Why the fuck are you using this outdated unmaintained fork of the renderer?
K-Lite includes latest version.
